apiVersion: iam.aws.crossplane.io/v1beta1
kind: Role
metadata:
  name: mec-new-eks-cluster-ngrole
spec:
  forProvider:
    assumeRolePolicyDocument: |
      {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Effect": "Allow",
                "Principal": {
                    "Service": [
                        "ec2.amazonaws.com"
                     ]
                 },
                 "Action": [
                     "sts:AssumeRole"
                 ]
            }
        ]
      }
  providerConfigRef:
    name: default
