apiVersion: eks.aws.crossplane.io/v1beta1
kind: Cluster
metadata:
  name: mec-new-eks-cluster
  labels:
    dev: "true"
spec:
  forProvider:
    region: us-west-2
    roleArnRef:
      name: mec-new-eks-cluster-role
    resourcesVpcConfig:
      endpointPrivateAccess: true
      endpointPublicAccess: true
      subnetIdRefs:
      - name: mec-new-eks-vpc-s1
      - name: mec-new-eks-vpc-s2
        #   securityGroupIdRefs:
        # - name: mec-new-eks-vpc-sg 
    version: "1.21"
  writeConnectionSecretToRef:
    name: cluster-conn
    namespace: default
  providerConfigRef:
    name: default
