apiVersion: ec2.aws.crossplane.io/v1beta1
kind: InternetGateway
metadata:
  name: mec-eks-vpc-igw
spec:
  forProvider:
    region: us-west-2
    vpcIdRef:
      name: mec-eks-vpc
  providerConfigRef:
    name: default
