apiVersion: kpt.dev/v1alpha1
kind: ResourceGroup
metadata:
  name: inventory-80831881
  namespace: default
  labels:
    cli-utils.sigs.k8s.io/inventory-id: ed8a7997dee120c8638b48ae98996c38b8ac5cde-1661096871554182848
