apiVersion: v1
kind: Service
metadata:
  name: coredns-caching
  annotations:
    prometheus.io/port: "9153"
    prometheus.io/scrape: "true"
  labels:
    package-instance: coredns-caching
  namespace: example
spec:
  selector:
    package-instance: coredns-caching
  ports:
  - name: dns
    port: 53
    protocol: UDP
  - name: dns-tcp
    port: 53
    protocol: TCP
  - name: metrics
    port: 9153
    protocol: TCP
