apiVersion: v1
kind: ConfigMap
metadata:
  name: kptfile.kpt.dev
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  name: nephio-edge-cluster-01
spec:
  git:
    repo: https://github.com/sandeepaarna/repo-edge-01
