---
apiVersion: v1
kind: Pod
metadata:
  name: shell-operator
spec:
  containers:
  - name: shell-operator
    image: sandeepaarna/shell-operator:nephio
    imagePullPolicy: Always
  serviceAccountName: nephio-shell-operator-acc
