---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nephio-shell-operator-acc

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: nephio-shell-operator
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: nephio-shell-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nephio-shell-operator
subjects:
  - kind: ServiceAccount
    name: nephio-shell-operator-acc
    namespace: nephio-shell-operator
