apiVersion: ec2.aws.crossplane.io/v1beta1
kind: RouteTable
metadata:
  name: mec-new-eks-vpc-rgt
  config.kubernetes.io/depends-on: vpc.ec2.aws.crossplane.io/VPC/mec-new-eks-vpc, vpc.ec2.aws.crossplane.io/InternetGateway/mec-new-eks-vpc-igw
spec:
  forProvider:
    region: us-west-2
    routes:
    - destinationCidrBlock: 0.0.0.0/0
      gatewayIdRef:
        name: mec-new-eks-vpc-igw
    associations:
    - subnetIdRef:
        name: mec-new-eks-vpc-s1
    - subnetIdRef:
        name: mec-new-eks-vpc-s2
    vpcIdRef:
      name: mec-new-eks-vpc
  providerConfigRef:
    name: default
